import { StartupProject, CurrencyCode } from '../../types/startup';
import { formatCurrency } from '../currency/currencies';

export function calculateBreakEven(
  unitSellingPrice: number,
  unitVariableCost: number,
  fixedMonthlyCost: number
) {
  const contributionMargin = Math.max(1, unitSellingPrice - unitVariableCost);
  const breakEvenUnits = Math.ceil((fixedMonthlyCost * 12) / contributionMargin);
  const breakEvenMonthlyRevenue = Math.round(breakEvenUnits * (unitSellingPrice / 12));
  return {
    contributionMargin,
    breakEvenUnits,
    breakEvenMonthlyRevenue,
  };
}

export function calculateValuation(
  projectedAnnualRevenue: number,
  growthRatePct: number,
  industry: string,
  stageIndex: number
) {
  // Revenue multiple model based on industry & stage
  let baseMultiple = 4.5;
  if (industry.toLowerCase().includes('ai') || industry.toLowerCase().includes('tech')) {
    baseMultiple = 7.0;
  } else if (industry.toLowerCase().includes('hardware') || industry.toLowerCase().includes('manufacturing')) {
    baseMultiple = 5.0;
  }

  const stageMultiplier = 0.5 + (stageIndex / 16) * 1.5;
  const growthMultiplier = 1 + (growthRatePct / 100) * 0.8;
  const calculatedValuation = Math.round(projectedAnnualRevenue * baseMultiple * stageMultiplier * growthMultiplier);
  return Math.max(5000000, calculatedValuation);
}

export function generateFullStartupReportMarkdown(startup: StartupProject, currency: CurrencyCode): string {
  const c = (amt: number) => formatCurrency(amt, currency, { compact: false });
  const compact = (amt: number) => formatCurrency(amt, currency, { compact: true });

  return `# ${startup.name} - Executive Venture Blueprint & IEEE SRS Report
**Generated by InnovAI Hub Enterprise Platform**
*Institutional Affiliation: ${startup.academicInfo.institution}*
*Presented By: ${startup.academicInfo.presenter} (${startup.academicInfo.studentId})*
*Supervisor: ${startup.academicInfo.supervisor}, ${startup.academicInfo.supervisorDesignation}*
*Mapped Sustainable Development Goals: SDG 9 (Primary), SDG 8, SDG 4*
*Date: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}*

---

## 1. Executive Summary & Problem-Solution Fit
- **Venture Name**: ${startup.name}
- **Founder(s)**: ${startup.founderName} ${startup.coFounders.length ? `(Co-Founders: ${startup.coFounders.join(', ')})` : ''}
- **Industry & Domain**: ${startup.industry}
- **Business Model**: ${startup.businessType}
- **Target Geography**: ${startup.country} / ${startup.targetMarket}
- **Current Lifecycle Stage**: Phase ${startup.currentPhaseIndex + 1} of 17
- **Overall Health Score**: ${startup.healthScore}/100 (${startup.healthGrade})
- **Estimated Business Valuation**: ${compact(startup.valuationEstimate)}
- **Runway**: ${startup.runwayMonths} Months (Monthly Burn: ${c(startup.monthlyBurnRate)})

### Problem Statement
${startup.problemStatement}

### Existing Alternatives & Inefficiencies
${startup.currentSolution}

### Proposed Innovation & Unique Value Proposition (UVP)
${startup.proposedSolution}

**Innovation Vector**: ${startup.uvpInnovation}

---

## 2. Market Sizing & Strategic Analysis (TAM / SAM / SOM)
- **Total Addressable Market (TAM)**: ${compact(startup.tamSamSom.tam)}
- **Serviceable Addressable Market (SAM)**: ${compact(startup.tamSamSom.sam)}
- **Serviceable Obtainable Market (SOM - 24 Mo)**: ${compact(startup.tamSamSom.som)}
- **Compound Annual Growth Rate (CAGR)**: ${startup.tamSamSom.cagrPct}% through ${startup.tamSamSom.forecastYear}

### SWOT Analysis
#### Strengths (Internal)
${startup.swot.strengths.map(s => `- ${s}`).join('\n')}

#### Weaknesses (Internal)
${startup.swot.weaknesses.map(w => `- ${w}`).join('\n')}

#### Opportunities (External)
${startup.swot.opportunities.map(o => `- ${o}`).join('\n')}

#### Threats (External)
${startup.swot.threats.map(t => `- ${t}`).join('\n')}

---

## 3. Porter's Five Forces Assessment
1. **Supplier Power**: ${startup.portersForces.supplierPower.level} - ${startup.portersForces.supplierPower.notes}
2. **Buyer Power**: ${startup.portersForces.buyerPower.level} - ${startup.portersForces.buyerPower.notes}
3. **Competitive Rivalry**: ${startup.portersForces.competitiveRivalry.level} - ${startup.portersForces.competitiveRivalry.notes}
4. **Threat of Substitution**: ${startup.portersForces.threatOfSubstitution.level} - ${startup.portersForces.threatOfSubstitution.notes}
5. **Threat of New Entrants**: ${startup.portersForces.threatOfNewEntrants.level} - ${startup.portersForces.threatOfNewEntrants.notes}

---

## 4. Competitor Benchmarking Matrix
| Competitor | Category | Market Share | Pricing | Key Vulnerability | InnovAI Moat |
| :--- | :--- | :--- | :--- | :--- | :--- |
${startup.competitors.map(comp => `| **${comp.name}** | ${comp.category} | ${comp.marketShare} | ${comp.pricingStrategy} | ${comp.criticalWeaknesses} | ${comp.innovAiMoat} |`).join('\n')}

---

## 5. Failure & Turnaround Audit (Why It May Fail & How to Fix It)
### Top Deadly Failure Vectors
${startup.failureAudit.topDeadlyVectors.map(fv => `### ${fv.vectorNum}: ${fv.title} [Severity: ${fv.severity}]
- **Risk Diagnostic**: ${fv.description}
- **Actionable Turnaround Remedy**: ${fv.actionableRemedy}
`).join('\n')}

### Unvalidated & Faulty Assumptions
${startup.failureAudit.unvalidatedAssumptions.map(ua => `- ${ua}`).join('\n')}

### Turnaround Action Playbook
| Phase | Strategic Action | Expected Milestone Outcome | Timeframe |
| :--- | :--- | :--- | :--- |
${startup.failureAudit.turnaroundPlan.map(tp => `| ${tp.phase} | ${tp.action} | ${tp.expectedOutcome} | ${tp.timeframe} |`).join('\n')}

---

## 6. Software Architecture & Requirements Specification (IEEE 830 Standard)
### System Perspective & Architectural Layers
- **Frontend Presentation Layer**: ${startup.techArchitecture.frontend.join(', ')}
- **Backend API & Microservices**: ${startup.techArchitecture.backend.join(', ')}
- **Database & Persistent State**: ${startup.techArchitecture.database.join(', ')}
- **Cloud Infrastructure & DevOps**: ${startup.techArchitecture.cloudDevops.join(', ')}
- **AI & Intelligent Service Engine**: ${startup.techArchitecture.aiEngine.join(', ')}
- **Cybersecurity & Safety Guardrails**: ${startup.techArchitecture.security.join(', ')}

### Software Licensing Budget
Total Monthly Software Tooling Cost: ${c(startup.softwareLicenses.reduce((acc, curr) => acc + (curr.isPaid ? curr.monthlyCost : 0), 0))}
| Tool / Service | Category | Monthly Cost | Purpose | Recommended Free Open Alternative |
| :--- | :--- | :--- | :--- | :--- |
${startup.softwareLicenses.map(lic => `| ${lic.name} | ${lic.category} | ${lic.isPaid ? c(lic.monthlyCost) : 'Free'} | ${lic.purpose} | ${lic.freeAlternative} |`).join('\n')}

---

${startup.isHardwareMode ? `## 7. Hardware & Factory Manufacturing Operations (Hardware Mode Active)
- **Unit Manufacturing Cost (BOM + SMT)**: ${c(startup.hardwareOps.unitManufacturingCost)}
- **Monthly Production Capacity**: ${startup.hardwareOps.monthlyProductionCapacity} Units
- **Factory Overhead (Monthly Rent + Utilities)**: ${c(startup.hardwareOps.factoryRentMonthly + startup.hardwareOps.utilitiesMonthly)}
- **Manufacturing Workforce**: ${startup.hardwareOps.workforceHeadcount} Technicians @ avg ${c(startup.hardwareOps.avgWorkerSalaryMonthly)}/month

### Bill of Materials (BOM)
| Component | Specification | Qty | Unit Cost | Lead Time |
| :--- | :--- | :--- | :--- | :--- |
${startup.hardwareOps.rawMaterials.map(b => `| ${b.component} | ${b.spec} | ${b.quantity} | ${c(b.unitCost)} | ${b.leadTimeDays} Days |`).join('\n')}
` : ''}

---

## 8. Financial Model, Unit Economics & 5-Year Forecasts
- **Monthly Cash Burn**: ${c(startup.monthlyBurnRate)}
- **Available Cash Runway**: ${startup.runwayMonths} Months
- **Customer Acquisition Cost (CAC)**: ${c(startup.unitEconomics.cac)}
- **Customer Lifetime Value (LTV)**: ${c(startup.unitEconomics.ltv)}
- **LTV / CAC Ratio**: ${startup.unitEconomics.ltvCacRatio}x (Healthy target > 3.0x)
- **Payback Period**: ${startup.unitEconomics.paybackMonths} Months
- **Break-Even Volume**: ${startup.breakEvenUnits} Units / year (${c(startup.breakEvenRevenueMonthly)} monthly revenue)

### 5-Year Multi-Year Financial Forecast
| Year | Projected Revenue | Cost of Goods Sold | Gross Profit | Operating Expenses | Net Profit (EBITDA) | Active Customers |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
${startup.financialForecasts.map(f => `| **Year ${f.year}** | ${compact(f.revenue)} | ${compact(f.costOfGoodsSold)} | ${compact(f.grossProfit)} | ${compact(f.operatingExpenses)} | ${compact(f.netProfit)} | ${f.customerCount.toLocaleString()} |`).join('\n')}

---

## 9. 10-Category Enterprise Risk & Mitigation Matrix
| Category | Identified Risk Factor | Probability | Impact | Risk Score | Mitigation & Contingency Plan |
| :--- | :--- | :--- | :--- | :--- | :--- |
${startup.riskMatrix.map(r => `| **${r.category}** | ${r.title} | ${r.probability} | ${r.impact} | ${r.riskScore}/10 | ${r.mitigationStrategy} |`).join('\n')}

---

## 10. Prioritized Next Actions ("What Should I Do Next?")
${startup.nextActions.map((na, idx) => `${idx + 1}. **${na.title}** [${na.priority} Priority]
   - *Category*: ${na.category} | *Est. Time*: ${na.estimatedTime} | *Est. Cost*: ${na.estimatedCost}
   - *Action Blueprint*: ${na.description}
   - *Key Deliverable*: ${na.deliverable}
`).join('\n')}

---

## 11. Academic Affiliation & References
- **Institution**: ${startup.academicInfo.institution} ${startup.academicInfo.institutionSubtitle}
- **Department**: ${startup.academicInfo.department}
- **Base Research Paper**: ${startup.academicInfo.basePaper.title} (${startup.academicInfo.basePaper.authors}, ${startup.academicInfo.basePaper.journal}, ${startup.academicInfo.basePaper.year}, DOI: ${startup.academicInfo.basePaper.doi})
- **Primary SDG Contribution**: SDG ${startup.academicInfo.sdgs[0].number} (${startup.academicInfo.sdgs[0].name})
`;
}
